[package]
name = "ai-image-webp"
version = "0.2.4"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.80.1"

description = "A no_std fork of image-webp"
homepage = "https://github.com/atom-planet-embrace/ai-image-webp"
repository = "https://github.com/atom-planet-embrace/ai-image-webp"
categories = ["multimedia::images", "multimedia::encoding", "encoding"]

include = ["/src", "LICENSE-APACHE", "LICENSE-MIT", "README.md"]

[dependencies]
no_std_io = { version = "0.6", default-features = false, features = ["alloc"] }
hashbrown = "0.15"

[dev-dependencies]
paste = "1.0.14"
png = "0.17.12"
rand = "0.8.5"
webp = "0.3.0"

[features]
std = ["no_std_io/std"]
_benchmarks = []
